services:
  app:
    image: shumc/imagor:latest
    volumes:
      - $PWD/data:/mnt/data
    restart: unless-stopped
    user: "1000:1000"
    environment:
      - IMAGOR_SECRET
      - HTTP_LOADER_ALLOWED_SOURCES
      - PORT=8000
      - FILE_LOADER_BASE_DIR=/mnt/data
      - FILE_STORAGE_BASE_DIR=/mnt/data
      - FILE_RESULT_STORAGE_BASE_DIR=/mnt/data/result
      - IMAGOR_UNSAFE=0
      - IMAGOR_AUTO_WEBP=1
      - IMAGOR_PROCESS_CONCURRENCY=${IMAGOR_PROCESS_CONCURRENCY:-16}
      - IMAGOR_PROCESS_QUEUE_SIZE=${IMAGOR_PROCESS_QUEUE_SIZE:-1500}
      - FILE_STORAGE_MKDIR_PERMISSION=0755
      - FILE_STORAGE_WRITE_PERMISSION=0666
      - FILE_RESULT_STORAGE_MKDIR_PERMISSION=0755
      - FILE_RESULT_STORAGE_WRITE_PERMISSION=0666
    networks:
      proxy_apps:

networks:
  proxy_apps:
    name: proxy_apps
    external: true